[package]
name = "bevy_sidescroller"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.16.1", features = ["dynamic_linking", "vorbis", "mp3"]}
bevy_rapier2d = {version = "0.30.0", features = ["simd-stable", "parallel"]}
